starkware-libs/starknet-specs

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/1)

adding block number to emitted event

---

api/starknet_api_openrpc.json
api/starknet_write_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/2)

write api: declare transaction

---

api/starknet_api_openrpc.json

v0.10.0: Introducing `getClassHash`, `getClassHashAt`, `getClassAt`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/3)

v0.10.0: get class, class hash, class at

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/4)

add estimateFee to the JSON RPC 

---

api/starknet_api_openrpc.json
api/starknet_write_api.json

some refactoring, following [this](https://starkwareindustries.slack.com/archives/D02FND7MEDP/p1654145791584109) discussion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/5)

Liors/sn api v0.12.0

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/6)

Refactor block structure and add pending block support

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/8)

Add NO_BLOCKS error.

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/13)

Remove block response scope options

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/15)

v0.20.0: add deploy transaction

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/16)

Fix get block functions and remove get block with receipts

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/17)

Change to block id

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/20)

Add block id to getClassAt

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/21)

Add declared contracts to state diff

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/23)

0.26: add a "type" field to transactions

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/24)

Remove timestamp from state update

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/25)

Update block and transaction status

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/32)

Change txn_hash to transaction_hash

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/30)

Add version, type, and contract_address_salt to deploy transaction

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/34)

add pending transaction receipt

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/35)

Add block_id to starknet_getNonce

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/41)

Removing protocol version method

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/26)

Pack storage diff entries per contract address

---

api/starknet_api_openrpc.json
api/starknet_write_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/42)

add invoke txn v1

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/43)

add abi to class

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/44)

paging via continuation token

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/45)

add l1_handler transaction

---

api/starknet_api_openrpc.json
api/starknet_write_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/46)

add broadcasted_txn type and unify write/estimateFee schemas

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/47)

using sender_address in v1 invoke txs

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/50)

Add invalid block id to get events

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/52)

Add invoke receipt properties to deploy receipt

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/53)

Remove redundant 'class_hash' in the array of declared contracts

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/55)

event filters to support multiple values

---

api/starknet_api_openrpc.json
api/starknet_write_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/57)

Add "DEPLOY_ACCOUNT" transaction

---

api/starknet_api_openrpc.json
api/starknet_write_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/59)

Bug fixes: tx type / abi type / bump write api version

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/58)

standardize address lengths at 64 bytes

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/61)

Change continuation token description

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/67)

Add required to components with required properties

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/68)

Make transaction type explicit

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/73)

add required to block_id

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/74)

add pending block state update

---

api/starknet_api_openrpc.json
api/starknet_trace_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/77)

bulk api: change estimateFee and simulate to take arrays

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/76)

state update: add replaced classes and rename properties

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/78)

rename sierra_version and add required

---

api/starknet_api_openrpc.json
api/starknet_trace_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/80)

Remove INVALID_MESSAGE_SELECTOR and INVALID_CALL_DATA from JSON RPC

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/82)

add required to declarev2 & add from_address to messages

---

api/starknet_api_openrpc.json
api/starknet_trace_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/99)

add reverted status

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/110)

add required to the properties of BROADCASTED_DECLARE_TXN_V1

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/112)

Fix SYNC_STATUS property types

---

api/starknet_api_openrpc.json
api/starknet_metdata.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/117)

add abi specs

---

api/starknet_api_openrpc.json
api/starknet_write_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/119)

Refine errors

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/121)

fix(RPC-SPEC): fix block transaction structure

---

api/starknet_api_openrpc.json
api/starknet_trace_api_openrpc.json
api/starknet_write_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/122)

Extract broadcasted declare txn out of the declare txn

---

api/starknet_trace_api_openrpc.json
api/starknet_write_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/126)

fix(api): fix references to other files

---

api/starknet_write_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/127)

fix(api): add required to write api's results

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/129)

fix: pending block & pending block w hash schema fix

---

api/starknet_api_openrpc.json
api/starknet_trace_api_openrpc.json
api/starknet_write_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/125)

reintroduce broadcasted txn & allow query version

---

api/starknet_write_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/136)

fix: typo fix

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/144)

fix: fix PENDING_STATE_UPDATE schema

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/142)

add missing fields to broadcasted_declare_txn_v1

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/145)

add missing fields to the pending block header

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/146)

fix: remove block hash from the pending block

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/147)

fix: fix execution_resources schema

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/150)

fix bug where all the schemas are vaild in the oneOf in PENDING_DEPLOY_TXN_RECEIPT

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/151)

allow EMITTED_EVENT contain pending events

---

api/starknet_trace_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/161)

Add state_diff to L1_HANDLER and DELEGATE call type

---

api/starknet_api_openrpc.json
api/starknet_trace_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/160)

Add syscall counters and resources to internal calls within a trace

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/165)

Add the segment arena builtin

---

api/starknet_api_openrpc.json
api/starknet_trace_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/135)

feat: error code for un-synced server

---

api/starknet_api_openrpc.json
api/starknet_trace_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/172)

Make trace fields optional & remove NODE_NOT_SYNCED

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/177)

Mandatory simulation flags in starknet_estimateFee

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/190)

fix: change l1_handler version to enum

---

api/starknet_api_openrpc.json
api/starknet_trace_api_openrpc.json
api/starknet_write_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/193)

fix: make data_gas related fields required in the block header

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/194)

fix: add 4844 fields to the pending block header

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/199)

fix storage key pattern

---

api/starknet_trace_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/201)

fix: add execution resources to l1 handler traces

---

api/starknet_api_openrpc.json
api/starknet_trace_api_openrpc.json
api/starknet_write_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/202)

bump version to 0.7.1

---

.editorconfig
api/starknet_api_openrpc.json
api/starknet_metadata.json
api/starknet_trace_api_openrpc.json
api/starknet_write_api.json
package.json
validate.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/212)

Add .editorconfig and format files

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/218)

Add error to getTransactionStatus

---

api/starknet_metadata.json

This PR resolves [#214](https://github.com/starkware-libs/starknet-specs/issues/214)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/215)

Add flat event field kind

---

api/starknet_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/230)

Update starknet_api_openrpc.json small typo

---

api/starknet_ws_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/238)

Ws socket errors

---

api/starknet_ws_api.json

Fix `params` for `starknet_subscriptionReorg`

Fix subscription reorg

---

api/starknet_api_openrpc.json
api/starknet_executables.json
api/starknet_metadata.json
api/starknet_trace_api_openrpc.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/244)

Fix typos in OpenRPC specifications

---

api/starknet_executables.json
package.json

Fix the schema to pass validate.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/247)

Fix starknet_executables api schema

---

api/starknet_ws_api.json

Adds the CALL_ON_PENDING error, finalizes #237 by @Trantorian1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/249)

add call on pending error

---

api/starknet_ws_api.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/268)

Remove block_id from transaction status

---

api/starknet_api_openrpc.json
api/starknet_executables.json
api/starknet_metadata.json
api/starknet_trace_api_openrpc.json
api/starknet_write_api.json
api/starknet_ws_api.json
wallet-api/wallet_rpc.json

Bump versions of all apis to v0.8.0-rc3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/274)

bump versions to rc3

---

README.md

Fix StarkNet -> Starknet (official name)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/124)

Fix StarkNet -> Starknet

---

api/starknet_api_openrpc.json
api/starknet_executables.json
api/starknet_metadata.json
api/starknet_trace_api_openrpc.json
api/starknet_write_api.json
api/starknet_ws_api.json
wallet-api/wallet_rpc.json

Bump all api versions to v0.8.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/283)

bump versions

---

api/starknet_write_api.json

Add errors for fee too low and underpriced replacement transaction

---

api/starknet_api_openrpc.json
api/starknet_executables.json
api/starknet_metadata.json
api/starknet_trace_api_openrpc.json
api/starknet_write_api.json
api/starknet_ws_api.json

Bump version

---

api/starknet_write_api.json

Make the spec OpenRPC compliant.

Fix nonce error structure

---

api/starknet_trace_api_openrpc.json

- Close #302
- Refactor to use a common component: `REVERTABLE_FUNCTION_INVOCATION`.

Add revert_reason to L1_HANDLER_TXN_TRACE

---

api/starknet_api_openrpc.json

Remove block_status rejected and docuentation mention of finality_status rejected.

Remove block_status rejected & mention from docs

---

api/starknet_api_openrpc.json
api/starknet_executables.json
api/starknet_metadata.json
api/starknet_trace_api_openrpc.json
api/starknet_write_api.json
api/starknet_ws_api.json

bump: v0.10.0-rc.0
