- api/starknet_api_openrpc.json
'type' is required in transaction receipt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/49)
> 0.2.0 fixes

- api/starknet_api_openrpc.json
- api/starknet_write_api.json
I'm trying to develop a codegen tool for automatically generating the JSON-RPC client code for `starknet-rs`. However, when parsing the specs, I encountered typos and structural inconsistencies that result in parsing errors. I'm submitting this PR for fixing them:
- Incorrectly laying out the fields directly instead of specifying `type` as `object` and putting them inside `properties`
- There's a typo of `ref` instead of `$ref`
- Incorrectly wrapping `$ref` inside another `schema` object when it should be laid flat
- Forgetting to specify `type` as `object` when `properties` is used
- Incorrectly specifying `type` as `object` when `oneOf` or `allOf` is used
- Forgetting to mark param as `required` in write APIs
Otherwise this PR makes no change to the actual specification.
> Fix typos and structure errors

- api/starknet_api_openrpc.json
- api/starknet_write_api.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/65)
> StarkNet 0.11.0 adjustments

- api/starknet_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/72)
> felt encoding: no leading zeros

- api/starknet_api_openrpc.json
Pretty sure those fields are optional. The current `pathfinder` implementation for `0.3` also treats them as optional:
https://github.com/eqlabs/pathfinder/blob/c802d9aea508fbaad0b80ba11f60e18e4c75cb3e/crates/rpc/src/v03/method/get_events.rs#L51_L67
I believe this is an error from #84.
> fix: `EVENT_FILTER` fields should be optional

- api/starknet_api_openrpc.json
Supersedes #60 as that PR is now updated.
We should add this field as `pathfinder` and `starknet-rs` have been forced to deviate from the specs for this anyways:
https://github.com/eqlabs/pathfinder/blob/c802d9aea508fbaad0b80ba11f60e18e4c75cb3e/crates/rpc/src/v02/types/class.rs#L378_L384
> fix: missing stateMutability in `FUNCTION_ABI_ENTRY`

- api/starknet_trace_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/104)
> rename argument in simulateTransaction & replace code_address by class_hash

- api/starknet_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/100)
> add starknet_estimateMessageFee endpoint

- api/starknet_trace_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/109)
> add SKIP_FEE_CHARGE flag to simulate

- api/starknet_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/108)
> change invoke v0: no nonce, add contract address

- api/starknet_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/107)
> Break status into execution status and finality status

- api/starknet_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/115)
> add selector to MSG_FROM_L1

- api/starknet_api_openrpc.json
- api/starknet_write_api.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/118)
> bugs fixes: add tx_hash, errors, and compiled_class_hash

- api/starknet_api_openrpc.json
- api/starknet_write_api.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/120)
> add declare v0

- api/starknet_api_openrpc.json
- api/starknet_trace_api_openrpc.json
- api/starknet_write_api.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/131)
> add v3 transactions and missing fields to receipts & block header

- api/starknet_api_openrpc.json
v0.5.0 will focus solely on the feeder gateway deprecation and aligning capabilities with the RPC, v3 transactions will be in the next version
> Remove v3 transcations

- api/starknet_api_openrpc.json
allows propagating errors from the blockifier or starknet_in_rust from the RPC
> add string data to CONTRACT_ERROR

- api/starknet_api_openrpc.json
Aligns the feeder gateway and the RPC - all the tx lifecycle should be visible through the RPC
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/140)
> add starknet_getTransactionStatus and remove starknet_pendingTransactions

- api/starknet_api_openrpc.json
- api/starknet_trace_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/149)
> v0.6.0: introduce v3 transactions

- api/starknet_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/162)
> Add v3 transactions additional fields

- api/starknet_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/164)
> Bound number properties and make builtin resources optional

- api/starknet_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/169)
> add stricter restrictions on v3 fields

- api/starknet_api_openrpc.json
This looks like a mistake it should be "0x1" for v1 transaction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/170)
> RPC 0.6 Fix declare txn v1 version

- api/starknet_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/175)
> add units to FEE_ESTIMATE

- api/starknet_api_openrpc.json
closes #158 
closes #159
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/173)
> typo fix and added property to schema object

- api/starknet_write_api.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/179)
> Add string data to validation error

- api/starknet_api_openrpc.json
- api/starknet_trace_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/187)
> Add data consumption to receipts and traces

- api/starknet_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/188)
> Add EIP-4844 related fields

- api/starknet_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/189)
> Add getBlockWithReceipts method

- api/starknet_api_openrpc.json
Removes the redundant block-related fields from the receipt, when appearing in a block with receipts request. To this end we're using the same objects that represent a transaction receipt in the pending block.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/191)
> refactor BLOCK_BODY_WITH_RECEIPTS

- api/starknet_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/195)
> fix receipt and pending receipt schema

- api/starknet_trace_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/198)
> add required to execution invocation when failed

- api/starknet_trace_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/200)
> add comment explaining execution_resources name is for legacy

- api/starknet_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/197)
> In TXN_RECEIPT, revert_reason is required if execution_status is REVERTED

- package.json
- wallet-api/wallet_rpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/203)
> Add wallet_rpc spec for wallet<>dapp communication

- api/starknet_api_openrpc.json
This PR removes the old "raw" execution resources (VM based, with low level info such as memory holes), and adds l2_gas to execution_resources.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/216)
> Adapt execution_resources to new receipt

- api/starknet_executables.json
Today, all nodes store the compiled CASM artifacts but do not externalize them. Third parties can use them and save the overhead of compilation, concrete usecases are:
- Replay startknet via a json-rpc based state reader, without the new endpoint replay time & complexity may be dominated by compilation
- Running the Starknet OS requires access to compiled CASM (this usecase also requires the `bytecode_segment_lengths` data, which is not stored ATM on nodes, hence it remains optional on the spec)
In this PR we add a `starknet_executables.json` section to the API, with a new endpoint to return the compiled CASM. The specification attempts to reflect the json serialization of [CasmContractClass](https://github.com/starkware-libs/cairo/blob/f1458c8726ad4aa5cedbeaac94027bd1c1d8c912/crates/cairo …
> Add GetCompiledCasm endpoint

- api/starknet_api_openrpc.json
The Starknet state commitment consists of three Merkle-Patricia tries (read more [here](https://docs.starknet.io/architecture-and-concepts/network-architecture/starknet-state/#merkle_patricia_trie)) :
- global state (leaf is a contract address)
- classes (leaf is the class hash)
- contracts storages (tree per contract)
This endpoint should return the data required to provide storage proofs in each of the relevant trees. Known use cases include:
- storage proofs
- running the starknet OS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/227)
> Add `getStorageProof` endpoint

- api/starknet_write_api.json
This error is only thrown when we did not pass the gateway, hence it should say we didn't have enough to cover for validate/minimal resources.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/217)
> Clarify the INSUFFICIENT_MAX_FEE error

- api/starknet_api_openrpc.json
Today, if an l1_handler transaction is rejected, there is no way for the sender to know why it failed other than manually computing the associated l1_handler transaction hash and querying its status. This endpoint basically does that for the user, by starting from the sending l1 transaction, and returning the status of all associated l1_handler transactions on Starknet (a single L1 transaction can send multiple messages)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/223)
> Add getMessagesStatus endpoint

- api/starknet_api_openrpc.json
- api/starknet_trace_api_openrpc.json
- api/starknet_write_api.json
- api/starknet_ws_api.json
- package-lock.json
- package.json
* Each subscription type is described by its own method, with relevant parameters. 
* The result of the subscription is a subscription ID, used to determine which stream a notification was received from, as well as an option to unsubscribe.
* For each subscription type, there is a notification method describing the results received in each streamed event
* A Reorg error is possible on all subscriptions, notifying that a reorg has occurred, and it is up to the client to treat this case according to their business logic
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/211)
> Starknet WebSocket specification proposal

- api/starknet_api_openrpc.json
In rpc <= 0.7.0, returned errors are strings encoding execution traces (used to be a lot of redundancy, e.g. scary "got an error while executing a hint" repeating a bunch of times, this should already be cleaner in starknet v0.13.2). Now that we have [more structure](https://github.com/starkware-libs/blockifier/blob/b22fb076a7db5e0fcdd2048a6fb579b0b1d25561/crates/blockifier/src/execution/syscalls/hint_processor.rs#L69) (also see [stack_trace.rs](https://github.com/starkware-libs/blockifier/blob/5bccf9ea34101388acb12edcc7d8c9c46f5b415f/crates/blockifier/src/execution/stack_trace.rs#L1)) in the blockifier, we can return the structured data and let sdks/wallets process it rather than rely on string manipulations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> Replace string with a structured error in CONTRACT_ERROR & TRANSACTION_EXECUTION_ERROR

- api/starknet_api_openrpc.json
The new changes from `v0.7.1` to `v0.8.0-rc0` are not consistent with the rest of the document. This PR fixes these issues:
- missing `required` field on a few `object` schemas;
- the `TXN_STATUS_RESULT` schema is incorrectly wrapped in another `schema` field;
- a type of `titel` contained in `CONTRACT_EXECUTION_ERROR`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/231)
> fix: schema conformance

- api/starknet_trace_api_openrpc.json
Since state diffs are squashed across the entire transaction, the l1_data_gas costs of an internal call are ill-defined. This PR removes them and also fixes the reference to the no-longer-existent COMPUTATION_RESOURCES object.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/233)
> Remove data gas from inner call resources

- api/starknet_api_openrpc.json
This PR makes the following changes to the `getStorageProof` endpoint:
- add `block_id` argument
- include storage proofs "metadata" for contracts, namely the nonce and class hash
- add the contracts and classes roots to the response
- changed MerkleNode to speak in terms of binary/edge/leaf node rather than in the (length, path, value) terminology
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/232)
> Refactor storage proofs

- api/starknet_executables.json
Minor fixes in `starknet_executables.json`.
- Fix indentation of `bytecode_segment_lengths` in `CASM_COMPILED_CONTRACT_CLASS`
- Fix title of Immediate
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/239)
> Fix `bytecode_segment_lengths` indentation; Fix Immediate title

- api/starknet_api_openrpc.json
And make `l2_gas_price` required in both pending and non-pending block headers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/236)
> fix: add `l2_gas_price` to PENDING_BLOCK_HEADER

- api/starknet_api_openrpc.json
- api/starknet_trace_api_openrpc.json
- api/starknet_ws_api.json
- validate.js
This does requires messages to be a list, which might not be what we want
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/235)
> Fix validation script after adding structured errors

- api/starknet_api_openrpc.json
ATM the transactions (as submitted through the write API) can't specify bounds for l1_data_gas. This PR adds l1_data_gas as a mandatory property to RESORUCE_BOUNDS_MAPPING.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/228)
> Add l1_data_gas to the resource bounds mapping

- api/starknet_ws_api.json
Continuing on the [discussion from Slack](https://spaceshard.slack.com/archives/C03QN20522D/p1731082431554749).
Closes #245 (someone please link the issue as closeable since I can't).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/246)
> Rename block param of ws methods to block_id

- api/starknet_ws_api.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/243)
> Fix `keys` ref in `starknet_subscribeEvents`

- .gitignore
- api/starknet_api_openrpc.json
- api/starknet_executables.json
- api/starknet_ws_api.json
- edited FEE_ESTIMATE.required 
- removed additional schema properties
- renamed dict_access -> dict_accesses
- DEPRECATED_CAIRO_ENTRY_POINT.offset type is integer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/257)
> v0.8.0 fixes

- wallet-api/wallet_rpc.json
This PR adds description to wallet behavior when the wallet is locked, or the Dapp is not yet approved by the wallet.
It also adds new error to handle cases when the no other information can be returned.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/261)
> Additional descriptions of wallet behaviors for wallet_rpc API

- validate.js
**{Map<string,string} - {Map<string,string>}**
> Change: Added missing > in type definition
Explanation: Fixed JSDoc syntax by adding the missing closing angle bracket in the Map type definition
Impact of the typo:
IDE type checking may fail or work incorrectly
Documentation generators might fail to parse the type
TypeScript compilation could fail if using TypeScript
Auto-completion features might not work properly
Could cause confusion for other developers reading the code
**Change: Fixed typo in dereferncer → dereferencer**
> Explanation: Corrected the misspelling where 'n' and 'c' were transposed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/264)
> Fix JSDoc Type Syntax and Parameter Naming

- api/starknet_write_api.json
Today, compilation can fail due to various reasons. The most common ones are:
- artifact (class or compiled class) exceeds the bytecode/size limits described [here](https://docs.starknet.io/tools/limits-and-triggers/#current_limits)
- unapproved libfuncs are used
While the gateway responds with the compilation error, it is not forwarded to the RPC consumer which receives the opaque "compilation failed"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/251)
> Refine compilation error in the write api

- api/starknet_api_openrpc.json
- api/starknet_ws_api.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/250)
> Add txn_with_hash component and update ws api

- api/starknet_api_openrpc.json
In some usecases, a storage proof for a contract is required without any particular storage keys, e.g. in the case of deployment with no storage updates. The current response structure is missing the contract storage trie root for those cases (it only exists implicitly in the response upon requesting a proof for a specific storage slot).
To remedy this, we add the `storage_root` property to `contract_leaves_data`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/265)
> Add storage_root to contracts leaf data

- api/starknet_trace_api_openrpc.json
As of Starknet v0.13.4, contracts can errors in called contracts (the entire transaction is not necessarily reverted). This means that we now need the execution status at the inner-call level to distinguish failed calls from successful ones.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/266)
> Add is_reverted to internal calls within the trace

- api/starknet_api_openrpc.json
While irrelevant for endpoints that receive a transaction (whose entrypoints are fixed), the `starknet_call` endpoint is the only method that is expected to start at a given selector. Nodes today can already distinguish this error from execution errors, hence it is reasonable to add `ENTRYPOINT_NOT_FOUND` to `starknet_call`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/267)
> Add ENTRYPOINT_NOT_FOUND error to starknet_call

- api/starknet_api_openrpc.json
In Starknet v0.14.0, only v3 transactions that sign all three resources will be supported. To help prepare the ecosystem, we remove v<3 transactions support from the write API, simulation, and fee estimation. Old transaction versions will only appear in the JSON-RPC to accommodate existing blocks on the network.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/269)
> Remove old transaction support from the write api

- api/starknet_ws_api.json
Adds a new type, SUBSCRIPTION_BLOCK_ID, similar to BLOCK_ID, but without `pending`. This will become redundant in 0.14.0, when both will converge.
* Removes the CALL_ON_PENDING error
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/272)
> Remove option for pending from all subsriptions

- api/starknet_trace_api_openrpc.json
In past versions of the json-rpc and Starknet, the behavior of execution resources within the trace was the following: the computation resources for every call is actually the resources of the subtree rooted at this call.
While not intuitive, this behavior originates in the blockifier structure, and will probably change in future versions. For the time being, we modify the description to clarify the existing semantics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/273)
> Update inner-call resources description

- api/starknet_api_openrpc.json
v0.8.0-rc2 includes a change of `offset` within the entrypoints of deprecated classes from NUM_AS_HEX to integers.
While integer does make more sense, we wish to avoid changes for deprecated offsets, which are already served in the "bad" way in older rpc versions. In particular, v0.8.0 is bound to Starknet v0.13.4, hence we want node teams to focus on critical changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/275)
> Revert entry point offset change

- api/starknet_api_openrpc.json
`estimateFee` receives `BROADCASTED_TXN` which are only `v3` in `v0.8.0`, so remove description for `v0-2`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/277)
> Update description for `starknet_estimateFee`

- api/starknet_executables.json
The integer --> NUM_AS_HEX rollback was supposed to affect only Cairo0 classes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/278)
> Change entrypoint offset type for new classes

- api/starknet_executables.json
I believe the correct one is `dict_accesses`. Am I right?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/280)
> Update starknet_executables.json, fix 'dict_access'

- api/starknet_executables.json
The summary was copied from the getClass method and is not updated, closes #279
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/281)
> Fix summary of starknet_getCompiledCasm

- api/starknet_api_openrpc.json
As the title suggets, storage proofs from the pending block are not well defined and may result in inconsistency between requests and node implementations
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/282)
> Disallow storage proof requests from the pending block

- api/starknet_write_api.json
This PR removes the explicit mention of max_fee field from the INSUFFICIENT_ACCOUNT_BALANCE text.
Closes #284
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/285)
> Update INSUFFICIENT_ACCOUNT_BALANCE error text

- api/starknet_ws_api.json
To secure arbitrary shape and form (ex. 'large number' strings) for subscription_id, as so for js to support it should be a string.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/288)
> fix: change subscription_id from integer to string

- api/starknet_api_openrpc.json
- api/starknet_executables.json
- api/starknet_metadata.json
- api/starknet_trace_api_openrpc.json
- api/starknet_write_api.json
- api/starknet_ws_api.json
subscription_id type is changed from integer to SUBSCRIPTION_ID
change version from 0.8.0 to 0.8.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/296)
> Change subscription_id parameter type of starknet_unsubscribe

- api/starknet_api_openrpc.json
The correct transaction status for L1 handler transactions in the pre-confirmed block is `PRE_CONFIRMED`, so we should allow that value.
> fix: allow `PRE_CONFIRMED` status in `starknet_getMessagesStatus` response

- api/starknet_api_openrpc.json
Update `starknet_getMessagesStatus` to use `TXN_FINALITY_STATUS` type in the `finality_status` field since they have the same values.
> Update `starknet_getMessagesStatus` to use `TXN_FINALITY_STATUS`

- api/starknet_api_openrpc.json
Add `l1_accepted` block tag. This tag refers to the latest Starknet block which is included in a state update on L1 and finalized by the consensus on L1.
> Add `l1_accepted` block tag

- api/starknet_ws_api.json
- [] Performed code self-review
> Add subscriptions for pre-confirmed transactions

- api/starknet_ws_api.json
starknet_subscriptionEvents result params specify a union of object and string value that should be a key-value pair.
> Rc3 params fix

- api/starknet_ws_api.json
The `TXN_FINALITY_STATUS` structure is not defined in the file where it is referenced.
> Fix TXN_FINALITY_STATUS reference in starknet_ws_api.json

- api/starknet_api_openrpc.json
starknet_getStorageProof using STORAGE_KEY instead of FELT
https://github.com/starkware-libs/starknet-specs/issues/259
> fix: param type of storage_keys

- api/starknet_api_openrpc.json
pathfinder currently returns `CONTRACT_NOT_FOUND` if `starknet_estimateMessageFee` is called with an invalid 
`MSG_FROM_L1.to_address` (see https://github.com/eqlabs/pathfinder/issues/2953 ), which seems semantically correct and useful to distinguish from `CONTRACT_ERROR` (see https://github.com/eqlabs/pathfinder/blob/main/crates/rpc/src/method/estimate_message_fee.rs#L102) but technically isn't allowed.
> fix: allow `CONTRACT_NOT_FOUND` error for `starknet_estimateMessageFee`
